name: chat

services:
  pg:
    image: bitnami/postgresql:17.2.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=chat
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local